config/routes.rb
Rails.application.routes.draw do
  resources :products, only: [:index, :show]
  root 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
# app/controllers/products_controller.rb

class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StoreApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<div class="container mt-5">
  <h1 class="text-center mb-4">Products</h1>

  <div class="row">
    <% @products.each do |product| %>
      <div class="col-md-4">
        <div class="card mb-4 product">
          <div class="card-body">
            <%= link_to product.name, product_path(product), class: "card-title stretched-link h2" %>
            <p class="card-text mt-3">Price: <%= number_to_currency(product.price) %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/products/show.html.erb
<div class="container mt-5">
  <div class="card product">
    <div class="card-body">
      <h2 class="card-title"><%= @product.name %></h2>
      <p class="card-text">Price: <%= number_to_currency(@product.price) %></p>
      <p class="card-text">Description: <%= @product.description %></p>
      <%= link_to 'Back to Products', products_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>